MUMU-For-Youth/MUMU_Backend

build.gradle, src/main/java/com/mumu/mumu/controller/KakaoLoginController.java, src/main/java/com/mumu/mumu/domain/Member.java, src/main/java/com/mumu/mumu/repository/MemberRepository.java, src/main/java/com/mumu/mumu/service/KakaoService.java
**설명 (필수)**
1. #8 
2. 변경 사항
- Member 및 MemberRepository 추가
- /callback 수정
- getAccessTokenFromKakao을 getTokenFromKakao로 수정
- Member 테이블에 저장하는 로직 추가
=> [CHORE] Insert user's tokens into RDS

src/main/java/com/mumu/mumu/controller/MapMarkerController.java, src/main/java/com/mumu/mumu/domain/Edu.java, src/main/java/com/mumu/mumu/domain/Space.java, src/main/java/com/mumu/mumu/dto/EduMarkerDTO.java, src/main/java/com/mumu/mumu/dto/SpaceMarkerDTO.java, src/main/java/com/mumu/mumu/repository/EducationRepository.java, src/main/java/com/mumu/mumu/repository/SpaceRepository.java, src/main/java/com/mumu/mumu/service/MapMarkerService.java
1. #11 
2. 변경 사항
- Marker 관련 세팅
- @youbing5921 과의 협업을 위한 domain/Edu & Space
**review 참고 사항 (선택)**
추가로 알릴 내용이 있다면 여기에 작성해주세요.
1. 문제 사항 있는지 검토 부탁드려욥
=> [Feat] Setting Entities about edu&space(IS RELATED TO #11)

src/main/java/com/mumu/mumu/domain/Edu.java, src/main/java/com/mumu/mumu/domain/Space.java
1. #11 
2. 변경 사항
- db snake cakse -> java camel case 하는 아래 명령어를 application.properties에서 주석처리
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
- 좌표값 설정 수정
=> [Fix] Setting Entities about edu&space(IS RELATED TO #11)

src/main/java/com/mumu/mumu/domain/Edu.java, src/main/java/com/mumu/mumu/domain/Member.java, src/main/java/com/mumu/mumu/domain/Space.java
1. IS RELATED TO #10 
2. 엔티티 컬럼명 DB와 연결되게 스네일체로 수정
=> [Fix] 엔티티 컬럼 이름 수정

src/main/java/com/mumu/mumu/controller/EduListController.java, src/main/java/com/mumu/mumu/dto/EduListResponseDto.java, src/main/java/com/mumu/mumu/repository/EduListRepository.java, src/main/java/com/mumu/mumu/service/EduListService.java, src/main/java/com/mumu/mumu/service/EduListServiceImpl.java, src/main/java/com/mumu/mumu/specification/EduListSpecification.java
1. IS RELATED TO #10 
2. 변경 사항
- /api/edu?region={region}&field={field}&status={status} API 구현
- status에 따른 쿼리는 아직 미완성
- 북마크 기능은 회원 관리할 때 수정할 예정.
=> [Feat] 무료교육 리스트 조회 구현

build.gradle, src/main/java/com/mumu/mumu/controller/MapMarkerController.java, src/main/java/com/mumu/mumu/dto/EduMarkerDTO.java, src/main/java/com/mumu/mumu/dto/SpaceMarkerDTO.java, src/main/java/com/mumu/mumu/exception/GlobalExceptionHandler.java, src/main/java/com/mumu/mumu/repository/EducationRepository.java, src/main/java/com/mumu/mumu/repository/SpaceRepository.java, src/main/java/com/mumu/mumu/service/MapMarkerService.java, src/main/java/com/mumu/mumu/specification/EduSpecification.java, src/main/java/com/mumu/mumu/specification/SpaceSpecification.java
**설명 (필수)**
1. #11 is Closed
2. 변경 사항
- 빈 값이거나 파라미터 자체가 없으면 해당 파라미터에 대해선 필터링 없음
- 리스트가 아니라 string으로 받되 내부적으로 쉼표 구분해서 처리함. 이에 프론트에서 쉼표로 구분해서 보내주시면 됨(notion 참고)
=> [Feat] Map Marker

src/main/java/com/mumu/mumu/controller/BookmarkController.java, src/main/java/com/mumu/mumu/domain/EduBookmark.java, src/main/java/com/mumu/mumu/domain/SpaceBookmark.java, src/main/java/com/mumu/mumu/dto/EduBookmarkDTO.java, src/main/java/com/mumu/mumu/dto/SpaceBookmarkDTO.java, src/main/java/com/mumu/mumu/repository/EduBookmarkRepository.java, src/main/java/com/mumu/mumu/repository/MemberRepository.java, src/main/java/com/mumu/mumu/repository/SpaceBookmarkRepository.java, src/main/java/com/mumu/mumu/service/BookmarkService.java
**설명 (필수)**
1. IS RELATED TO #20 
2. 변경 사항
- 북마크 ON/OFF 만들었음!
- GET은 특정 장소/교육에 대해 True/False로만 조회하는 중인데, 이후에 리스트 형태로 값 받아올 수 있게 수정할 예정.
=> [Feat] POST functions Completed(IS RELATED TO #20)

Dockerfile, docker-compose.yml, src/main/java/com/mumu/mumu/exception/GlobalExceptionHandler.java, src/main/resources/logback-spring.xml
1. #21 
2. 변경 사항
- docker 관련 파일들 추가
=> [CHORE]Docker related files for CI/CD

src/main/java/com/mumu/mumu/controller/EduListController.java, src/main/java/com/mumu/mumu/controller/SpaceListController.java, src/main/java/com/mumu/mumu/service/EduListService.java, src/main/java/com/mumu/mumu/service/EduListServiceImpl.java, src/main/java/com/mumu/mumu/service/SpaceListService.java, src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
**설명 (필수)**
1. RESOLVES #24 AND RESOLVES #10 
2. 변경 사항
- 기존에 marker에서 사용했던 로직을 바탕으로 쉼표/공백으로 데이터 필터링 가능하게 작업함
=> [Feat] Multiple Filtering w/ ,

src/main/java/com/mumu/mumu/controller/EduListController.java, src/main/java/com/mumu/mumu/controller/SpaceListController.java, src/main/java/com/mumu/mumu/dto/EduDetailResponseDto.java, src/main/java/com/mumu/mumu/dto/EduListResponseDto.java, src/main/java/com/mumu/mumu/dto/SpaceDetailResponseDto.java, src/main/java/com/mumu/mumu/dto/SpaceListResponseDto.java, src/main/java/com/mumu/mumu/service/EduListService.java, src/main/java/com/mumu/mumu/service/EduListServiceImpl.java, src/main/java/com/mumu/mumu/service/SpaceListService.java, src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
**설명 (필수)**
1. RESOLVES #30 
2. 변경 사항
- bookmarked를 기본값으로는 false로하되, accessToken을 optional하게 주면 그 멤버를 기준으로 true 확인
=> [Feat] bookmarked

src/main/java/com/mumu/mumu/dto/SpaceDetailResponseDto.java
=> [Fix] 공간 상세 조회 response 수정

src/main/java/com/mumu/mumu/dto/EduDetailResponseDto.java
교육 상세 페이지에서 띄우는 정보가 DTO와 달라 이를 수정함.
=> [Fix] 교육 상세 조회 response 수정

src/main/java/com/mumu/mumu/dto/SpaceListResponseDto.java
공간 리스트 조회에서 response에 공간 이미지 속성을 전해주지 않아 이를 수정함.
=> [Fix] 공간 리스트 조회 response 이미지 추가

src/main/java/com/mumu/mumu/dto/EduListResponseDto.java
교육 리스트 조회에서 response에 이미지 속성을 넘겨주지 않아 이를 추가함.
=> [Fix] 교육 리스트 조회 response 이미지 추가

src/main/java/com/mumu/mumu/dto/EduListResponseDto.java
교육 리스트 조회 DTO에 이미지 속성 추가하는 과정에서 생성자 1개에 누락되어 이를 추가함.
=> [Fix] 교육 리스트 조회 DTO 수정

src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
DB 속성에 spaceRegion이 아닌 region으로 되어 있는데 코드에 spaceRegion으로 되어 있어 이를 region으로 수정함.
=> [Fix] spaceRegion -> region 수정

src/main/java/com/mumu/mumu/controller/AuthController.java, src/main/java/com/mumu/mumu/controller/KakaoLoginController.java, src/main/java/com/mumu/mumu/controller/KakaoLoginPageController.java, src/main/java/com/mumu/mumu/service/KakaoService.java
- 카카오 로그인 URL 생성 api 구현
- 카카오 로그인 콜백 api 구현
- 리프레시 토큰으로 엑세스 토큰 갱신 api 구현
> 추가로 API 명세서 문서도 수정함.
=> [Feat] 카카오 로그인 api 수정

src/main/java/com/mumu/mumu/config/WebConfig.java
=> [CHORE] changing front url

src/main/java/com/mumu/mumu/config/WebConfig.java
=> [CHORE] changing front url2

src/main/java/com/mumu/mumu/config/WebConfig.java
https://mumu-for-youth.github.io로 변경
=> [CHORE] changing front url3

Dockerfile, nginx.conf, src/main/java/com/mumu/mumu/config/WebConfig.java, start.sh
**설명 (필수)**
1. 관련 이슈 없음
2. 변경 사항
- nginx 설정
- Route53으로 산 domain 주소 반영
=> [CHORE] Setting mumu domain

docker-compose.yml
8080:8080 -> 80:8080 in docer-compose.yml
=> [CHORE] Setting mumu domain as https2

src/main/java/com/mumu/mumu/config/WebConfig.java
- localhost:3000 관련 webconfig 파일 수정
=> [CHORE] allow localhost:3000 for dev

src/main/java/com/mumu/mumu/domain/SpaceTarget.java, src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java, src/main/java/com/mumu/mumu/specification/SpaceListSpecification.java
**설명 (필수)**
1. IS RELATED TO #48 
2. 변경 사항
- space target 관련 mapping
- 로직 수정
=> [Feat] Add Space

src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
=> [Fix] change type field type into spaceType

src/main/java/com/mumu/mumu/domain/Space.java, src/main/java/com/mumu/mumu/service/EduListServiceImpl.java, src/main/java/com/mumu/mumu/service/SpaceListServiceImpl.java
=> [Feat] OR conditions in each parameter & AND conditions between parameters

src/main/java/com/mumu/mumu/controller/KakaoLoginController.java, src/main/java/com/mumu/mumu/service/KakaoService.java
/auth/kakao/logout API 구현
**Check List :memo:**
**설명 (필수)**
1. #59 
2. POST /auth/kakao/logout API를 이용하여 로그아웃 기능 구현
=> [Feat] 로그아웃 구현

src/main/java/com/mumu/mumu/controller/KakaoLoginController.java
로그인 테스트를 위해 임시방편으로 localhost:3000과 연결함.
=> [Test] 프론트 로컬 서버로 로그인 연결

src/main/java/com/mumu/mumu/service/KakaoService.java
json에서 Content-Type: application/x-www-form-urlencoded;charset=utf-8
로 변경
=> [Fix] /auth/kakao/callback request 형식 변경

src/main/java/com/mumu/mumu/service/KakaoService.java
=> [Fix] redirect uri 통일
